/* =====================================================================
   GULF LUBRICATION INTELLIGENCE – CENTRAL DATA LAYER (PROTOTYPE)
   ---------------------------------------------------------------------
   ONE data model powers all seven modules. Nothing in app.js keeps its
   own copy of products, equipment or knowledge.

   Entity chain:
   OEM → Equipment/Model → Industry/Application → System → Operating
   Condition → Specification → Gulf Product → Technical Evidence →
   Oil Analysis → Maintenance → TCO → Lubrication Passport

   ALL VALUES ARE DEMO / ILLUSTRATIVE DATA. Product grades, specifications,
   intervals, capacities, prices, analysis limits and locations are
   placeholders that show the experience. They are not Gulf technical
   claims and must be replaced with validated data before production.

   PRODUCTION: each top-level key maps to an API resource, e.g.
   GET /api/products, /api/equipment, /api/knowledge, /api/oil-analysis.
   ===================================================================== */
const slugify = s => String(s).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

const gulfData = {
  // ---- Vocabularies -------------------------------------------------
  categories: { MCO:'Motorcycle Oils', PCMO:'Passenger Car Motor Oils', CVO:'Commercial Vehicle Oils', GEAR:'Gear & Transmission Oils', HYD:'Hydraulic Fluids', AGRI:'Agricultural Lubricants', IND:'Industrial Lubricants', GREASE:'Greases', EV:'EV Fluids' },
  systems: [
    { id:'engine', name:'Engine', fluid:'Engine oil', icon:'🛢️' },
    { id:'hydraulic', name:'Hydraulic', fluid:'Hydraulic fluid', icon:'🔧' },
    { id:'transmission', name:'Transmission', fluid:'Transmission oil', icon:'⚙️' },
    { id:'differential', name:'Differential', fluid:'Axle / gear oil', icon:'🔩' },
    { id:'grease', name:'Grease points', fluid:'Grease', icon:'🧴' },
    { id:'gearbox', name:'Industrial gearbox', fluid:'Industrial gear oil', icon:'⚙️' },
    { id:'compressor', name:'Compressor', fluid:'Compressor oil', icon:'💨' },
    { id:'turbine', name:'Turbine', fluid:'Turbine oil', icon:'🌀' },
    { id:'ev', name:'EV driveline', fluid:'EV fluid', icon:'🔋' }
  ],
  // Operating conditions and problems share one tag vocabulary.
  conditions: [
    { id:'normal', name:'Normal operation' }, { id:'heavy', name:'Heavy duty' }, { id:'hot', name:'High temperature' },
    { id:'dusty', name:'Dusty environment' }, { id:'longhours', name:'Long operating hours' }, { id:'startstop', name:'Frequent start/stop' },
    { id:'longdrain', name:'Long drain interval' }, { id:'fuel', name:'Fuel efficiency' }, { id:'wear', name:'Wear protection' },
    { id:'corrosion', name:'Corrosion protection' }, { id:'hydraulic', name:'Hydraulic performance' }
  ],
  problems: [
    { id:'high-oil-temperature', name:'High oil temperature', tag:'hot', icon:'🌡️', article:'high-oil-temperature-causes' },
    { id:'heavy-load', name:'Heavy load', tag:'heavy', icon:'🏋️', article:'choosing-diesel-engine-oil-viscosity' },
    { id:'dust-contamination', name:'Dusty environment', tag:'dusty', icon:'🌫️', article:'silicon-and-dust-ingress' },
    { id:'frequent-start-stop', name:'Frequent start/stop', tag:'startstop', icon:'🚦', article:'lubrication-basics-what-oil-does' },
    { id:'long-drain-interval', name:'Long drain interval', tag:'longdrain', icon:'⏱️', article:'extending-drain-intervals-safely' },
    { id:'fuel-efficiency', name:'Fuel efficiency', tag:'fuel', icon:'⛽', article:'choosing-diesel-engine-oil-viscosity' },
    { id:'wear-protection', name:'Wear protection', tag:'wear', icon:'🛡️', article:'high-iron-in-engine-oil' },
    { id:'corrosion-protection', name:'Corrosion protection', tag:'corrosion', icon:'💧', article:'reading-an-oil-analysis-report' },
    { id:'hydraulic-performance', name:'Hydraulic performance', tag:'hydraulic', icon:'🔧', article:'hydraulic-oil-overheating' }
  ],
  industries: [
    { id:'construction', name:'Construction', icon:'🏗️' }, { id:'mining', name:'Mining', icon:'⛏️' },
    { id:'agriculture', name:'Agriculture', icon:'🌾' }, { id:'transport', name:'Transport & Fleet', icon:'🚛' },
    { id:'manufacturing', name:'Manufacturing', icon:'🏭' }, { id:'power', name:'Power', icon:'⚡' },
    { id:'material-handling', name:'Material Handling', icon:'📦' }, { id:'automotive', name:'Personal Mobility', icon:'🚗' }
  ],
  applications: [
    { id:'engine-lubrication', name:'Engine lubrication', system:'engine' },
    { id:'hydraulic-systems', name:'Hydraulic systems', system:'hydraulic' },
    { id:'transmissions', name:'Transmissions', system:'transmission' },
    { id:'axles-and-differentials', name:'Axles and differentials', system:'differential' },
    { id:'bearings-and-greasing', name:'Bearings and greasing', system:'grease' },
    { id:'industrial-gear-drives', name:'Industrial gear drives', system:'gearbox' },
    { id:'air-compressors', name:'Air compressors', system:'compressor' },
    { id:'turbines', name:'Turbines', system:'turbine' },
    { id:'ev-drivelines', name:'EV drivelines', system:'ev' },
    { id:'construction', name:'Construction equipment', industry:'construction' },
    { id:'farm-equipment', name:'Farm equipment', industry:'agriculture' },
    { id:'fleet-operations', name:'Fleet operations', industry:'transport' }
  ],
  oems: [
    { id:'jcb', name:'JCB' }, { id:'cat', name:'CAT' }, { id:'komatsu', name:'Komatsu' }, { id:'mahindra', name:'Mahindra' },
    { id:'john-deere', name:'John Deere' }, { id:'swaraj', name:'Swaraj' }, { id:'tata-motors', name:'Tata Motors' },
    { id:'ashok-leyland', name:'Ashok Leyland' }, { id:'atlas-copco', name:'Atlas Copco' }, { id:'elecon', name:'Elecon' },
    { id:'cummins', name:'Cummins' }, { id:'maruti-suzuki', name:'Maruti Suzuki' }, { id:'hero', name:'Hero' }, { id:'honda', name:'Honda' },
    { id:'generic', name:'Generic / any OEM' }
  ],

  // ---- Products (DEMO DATA) -----------------------------------------
  // price = illustrative ₹ per litre (or per kg for grease); position = indicative cost position.
  products: [
    { id:'pride-4t', name:'Gulf Pride 4T Plus', category:'MCO', systems:['engine'], grade:'10W-30', specs:['API SN','JASO MA2'], tags:['normal','startstop','wear','fuel'], industries:['automotive'], price:380, position:'Mid', base:'Part-synthetic (demo)', applications:['Commuter motorcycles','4-stroke engines with wet clutch'], benefits:['Smooth clutch feel in city riding','Protection in stop-go traffic','Supports fuel economy'], description:'Everyday 4-stroke motorcycle engine oil for commuter bikes.' },
    { id:'pride-scooter', name:'Gulf Pride Scooter', category:'MCO', systems:['engine'], grade:'10W-30', specs:['API SL','JASO MB'], tags:['normal','startstop','fuel'], industries:['automotive'], price:360, position:'Mid', base:'Part-synthetic (demo)', applications:['Automatic scooters','Gearless scooter engines'], benefits:['Tuned for scooter engines','Easy starts on short trips','Supports fuel economy'], description:'Engine oil formulated for automatic scooters.' },
    { id:'syntrac-4t', name:'Gulf Syntrac 4T', category:'MCO', systems:['engine'], grade:'10W-40', specs:['API SN','JASO MA2'], tags:['hot','heavy','wear','longdrain'], industries:['automotive'], price:620, position:'Premium', base:'Synthetic (demo)', applications:['Premium and performance motorcycles'], benefits:['Holds viscosity at high temperature','Wear protection at high revs','Extended drain capability'], description:'Synthetic 4-stroke oil for premium and performance motorcycles.' },
    { id:'formula-gx', name:'Gulf Formula GX', category:'PCMO', systems:['engine'], grade:'5W-30', specs:['API SP','ACEA C3'], tags:['normal','hot','wear','longdrain','startstop'], industries:['automotive','transport'], price:650, position:'Premium', base:'Synthetic (demo)', applications:['Petrol and diesel passenger cars','BS-VI diesel engines with after-treatment'], benefits:['Compatible with after-treatment systems','Protection in stop-start driving','Extended drain capability'], description:'Synthetic engine oil for modern petrol and diesel passenger cars.' },
    { id:'ultrasynth-x', name:'Gulf Ultrasynth X', category:'PCMO', systems:['engine'], grade:'0W-20', specs:['API SP','ILSAC GF-6'], tags:['fuel','startstop','normal','wear'], industries:['automotive'], price:780, position:'Premium', base:'Synthetic (demo)', applications:['Modern petrol and hybrid passenger cars'], benefits:['Low viscosity for fuel efficiency','Fast flow at cold start','Protection for turbo petrol engines'], description:'Low-viscosity synthetic oil for modern petrol and hybrid cars.' },
    { id:'multi-g', name:'Gulf Multi G', category:'PCMO', systems:['engine'], grade:'20W-50', specs:['API SL'], tags:['normal','hot','wear'], industries:['automotive'], price:340, position:'Value', base:'Mineral (demo)', applications:['Older petrol passenger cars','Higher-mileage engines'], benefits:['Thicker film for older engines','Helps control oil consumption','Reliable everyday protection'], description:'Multigrade engine oil for older and higher-mileage cars.' },
    { id:'superfleet-supreme', name:'Gulf Superfleet Supreme', category:'CVO', systems:['engine'], grade:'15W-40', specs:['API CK-4','ACEA E9'], tags:['normal','heavy','hot','dusty','longhours','wear'], industries:['transport','construction','mining','power','material-handling'], price:360, position:'Mid', base:'Premium mineral (demo)', applications:['BS-VI diesel engines for trucks and buses','Construction and off-highway diesel engines'], benefits:['Soot and deposit control under heavy load','Stable viscosity at high temperature','Wear protection in dusty sites','Compatible with after-treatment systems'], description:'Heavy-duty diesel engine oil for on-road fleets and off-highway equipment.' },
    { id:'superfleet-synth', name:'Gulf Superfleet Synth', category:'CVO', systems:['engine'], grade:'10W-40', specs:['API CK-4','ACEA E6'], tags:['heavy','hot','longdrain','longhours','fuel'], industries:['transport','construction','mining','power'], price:520, position:'Premium', base:'Synthetic (demo)', applications:['Long-haul trucks and buses','High-utilisation diesel engines'], benefits:['Extended drain capability','Fuel-economy benefit from lower viscosity','Protection across long duty cycles'], description:'Synthetic heavy-duty diesel engine oil for long-drain operation.' },
    { id:'super-duty', name:'Gulf Super Duty CF-4', category:'CVO', systems:['engine'], grade:'15W-40', specs:['API CI-4'], tags:['normal','heavy','dusty','wear'], industries:['transport','construction','mining','agriculture','power','material-handling'], price:300, position:'Value', base:'Mineral (demo)', applications:['Older diesel trucks and tractors','Gensets and stationary diesel engines'], benefits:['Proven protection for older diesel engines','Controls wear in dusty operation','Value option for mixed fleets'], description:'Diesel engine oil for older commercial vehicles, gensets and equipment.' },
    { id:'gear-ep', name:'Gulf Gear EP', category:'GEAR', systems:['transmission','differential'], grade:'80W-90', specs:['API GL-5'], tags:['normal','heavy','wear','hot'], industries:['transport','construction','mining','agriculture','material-handling','automotive'], price:330, position:'Mid', base:'Mineral (demo)', applications:['Axles and differentials','Manual gearboxes where GL-5 is specified'], benefits:['Extreme-pressure protection for loaded gears','Resists thermal breakdown','Protects against scuffing and wear'], description:'Extreme-pressure gear oil for axles, differentials and gearboxes.' },
    { id:'harmony-aw', name:'Gulf Harmony AW', category:'HYD', systems:['hydraulic'], grade:'ISO VG 68', specs:['ISO VG 68','DIN 51524-2 HLP'], tags:['normal','heavy','hydraulic','wear','corrosion'], industries:['construction','mining','manufacturing','material-handling','agriculture','power'], price:240, position:'Value', base:'Mineral (demo)', applications:['Hydraulic systems in mobile and industrial equipment','Hydraulic presses and power packs'], benefits:['Anti-wear protection for pumps','Rust and corrosion protection','Good filterability'], description:'Anti-wear hydraulic fluid for industrial and mobile hydraulic systems.' },
    { id:'harmony-hvi', name:'Gulf Harmony HVI', category:'HYD', systems:['hydraulic'], grade:'ISO VG 46', specs:['ISO VG 46','DIN 51524-3 HVLP'], tags:['hot','hydraulic','longhours','heavy','dusty','wear'], industries:['construction','mining','manufacturing','material-handling'], price:310, position:'Mid', base:'Mineral, high VI (demo)', applications:['Mobile hydraulics with wide temperature swings','Excavators, loaders and cranes'], benefits:['High viscosity index for hot and cold operation','Consistent hydraulic response','Pump protection over long shifts'], description:'High-viscosity-index hydraulic fluid for mobile equipment in demanding sites.' },
    { id:'utto', name:'Gulf Universal Tractor Transmission Oil', category:'AGRI', systems:['transmission','hydraulic'], grade:'10W-30', specs:['API GL-4'], tags:['normal','heavy','hydraulic','wear'], industries:['agriculture','construction'], price:290, position:'Mid', base:'Mineral (demo)', applications:['Tractor transmissions, hydraulics and wet brakes'], benefits:['One fluid for transmission, hydraulics and wet brakes','Smooth wet-brake operation','Gear and pump wear protection'], description:'Universal tractor transmission oil for transmissions, hydraulics and wet brakes.' },
    { id:'tractor-engine', name:'Gulf Tractor Engine Oil', category:'AGRI', systems:['engine'], grade:'15W-40', specs:['API CI-4'], tags:['normal','heavy','dusty','longhours','wear'], industries:['agriculture'], price:310, position:'Value', base:'Mineral (demo)', applications:['Tractor diesel engines','Harvesters and farm equipment'], benefits:['Protection in dusty field conditions','Handles long working days in season','Controls soot and deposits'], description:'Diesel engine oil for tractors and farm equipment.' },
    { id:'ep-lubricant', name:'Gulf EP Lubricant HD', category:'IND', systems:['gearbox'], grade:'ISO VG 220', specs:['ISO VG 220','DIN 51517-3 CLP'], tags:['heavy','wear','hot','corrosion','longhours'], industries:['manufacturing','mining','power','material-handling'], price:280, position:'Mid', base:'Mineral (demo)', applications:['Industrial gearboxes','Enclosed gear drives on conveyors and mills'], benefits:['Extreme-pressure protection for loaded gears','Resists micropitting and wear','Rust and corrosion protection'], description:'Extreme-pressure industrial gear oil for enclosed gear drives.' },
    { id:'compressor-oil', name:'Gulf Compressor Oil', category:'IND', systems:['compressor'], grade:'ISO VG 46', specs:['ISO VG 46','DIN 51506 VDL'], tags:['hot','longhours','wear','corrosion','normal'], industries:['manufacturing','power','mining'], price:340, position:'Mid', base:'Mineral (demo)', applications:['Rotary screw air compressors','Reciprocating air compressors'], benefits:['Resists oxidation at high discharge temperature','Low deposit formation','Water separation'], description:'Demo listing for an air compressor oil.' },
    { id:'turbine-oil', name:'Gulf Turbine Oil', category:'IND', systems:['turbine'], grade:'ISO VG 32', specs:['ISO VG 32','DIN 51515-1 TD'], tags:['longhours','corrosion','hot','normal'], industries:['power','manufacturing'], price:360, position:'Mid', base:'Mineral (demo)', applications:['Steam and gas turbine bearings','Turbine control systems'], benefits:['Long oxidation life','Air release and water separation','Rust protection'], description:'Demo listing for a turbine oil.' },
    { id:'crown-lc', name:'Gulf Crown LC 2', category:'GREASE', systems:['grease'], grade:'NLGI 2', specs:['NLGI 2'], tags:['normal','heavy','hot','dusty','corrosion','wear'], industries:['transport','construction','mining','agriculture','manufacturing','power','material-handling','automotive'], price:420, position:'Mid', base:'Lithium complex (demo)', applications:['Wheel bearings, pins and bushes','General industrial and automotive greasing'], benefits:['Stays in place under load','Seals out dust and water','Wide temperature range'], description:'Multipurpose lithium-complex grease for bearings, pins and bushes.' },
    { id:'elec-driveline', name:'Gulf eLEC Driveline Fluid', category:'EV', systems:['ev'], grade:'Low-viscosity e-fluid', specs:['Demo e-fluid specification'], tags:['fuel','wear','hot','normal'], industries:['automotive','transport'], price:900, position:'Premium', base:'Synthetic (demo)', applications:['EV reduction gearboxes and e-axles'], benefits:['Low viscosity for driveline efficiency','Material and electrical compatibility focus','Gear and bearing protection'], description:'Concept listing for an EV driveline fluid. Scope to be confirmed with the Gulf technical team.' }
  ],

  // ---- Equipment and vehicles (DEMO DATA) ---------------------------
  // lubrication: per system → ordered candidate products, sump capacity (L) and service interval (hours). All demo values.
  equipment: (() => {
    const L = (system, products, capacity, interval) => ({ system, products, capacity, interval });
    const mobile = (eng, hyd) => [L('engine', ['superfleet-supreme','superfleet-synth','super-duty'], eng, 500), L('hydraulic', ['harmony-hvi','harmony-aw'], hyd, 2000), L('transmission', ['gear-ep','utto'], 18, 1000), L('differential', ['gear-ep'], 14, 1000), L('grease', ['crown-lc'], 1, 50)];
    const tractor = [L('engine', ['tractor-engine','super-duty'], 8, 250), L('transmission', ['utto'], 40, 1000), L('hydraulic', ['utto','harmony-aw'], 40, 1000), L('grease', ['crown-lc'], 1, 50)];
    const truck = [L('engine', ['superfleet-supreme','superfleet-synth','super-duty'], 22, 500), L('transmission', ['gear-ep'], 12, 1500), L('differential', ['gear-ep'], 16, 1500), L('grease', ['crown-lc'], 1, 100)];
    const E = (oem, model, type, group, kind, industry, engine, environment, tags, lubrication, name) => ({ id: oem === 'generic' ? slugify(model) : oem + '-' + slugify(model), oem, slug: slugify(model), model, type, group, kind, industry, engine, environment, tags, lubrication, name });
    return [
      E('jcb','3DX','Backhoe Loader','Construction','equipment','construction','Diesel, turbocharged (demo data)','Construction / Heavy duty',['heavy','hot','dusty'], mobile(14, 130), 'JCB 3DX'),
      E('jcb','4DX','Backhoe Loader','Construction','equipment','construction','Diesel, turbocharged (demo data)','Construction / Heavy duty',['heavy','dusty'], mobile(14, 140), 'JCB 4DX'),
      E('cat','320D','Excavator','Construction','equipment','construction','Diesel, turbocharged (demo data)','Construction / Heavy duty',['heavy','hot','longhours'], mobile(25, 260), 'CAT 320D'),
      E('komatsu','PC210','Excavator','Construction','equipment','construction','Diesel, turbocharged (demo data)','Construction / Mining',['heavy','dusty','longhours'], mobile(24, 250), 'Komatsu PC210'),
      E('cat','950','Wheel Loader','Construction','equipment','construction','Diesel, turbocharged (demo data)','Construction / Quarry',['heavy','dusty'], mobile(30, 180), 'CAT 950'),
      E('mahindra','575 DI','Tractor','Agriculture','equipment','agriculture','Diesel (demo data)','Farm / Dusty field work',['dusty','heavy','longhours'], tractor, 'Mahindra 575 DI'),
      E('swaraj','744 FE','Tractor','Agriculture','equipment','agriculture','Diesel (demo data)','Farm / Haulage',['dusty','heavy'], tractor, 'Swaraj 744 FE'),
      E('john-deere','W70','Combine Harvester','Agriculture','equipment','agriculture','Diesel (demo data)','Harvest season / Long days',['dusty','longhours','hot'], tractor, 'John Deere W70'),
      E('tata-motors','Signa','Truck','Commercial Vehicles','vehicle','transport','Diesel, BS-VI (demo data)','Long haul / Heavy load',['heavy','longhours','longdrain'], truck, 'Tata Signa'),
      E('ashok-leyland','Viking','Bus','Commercial Vehicles','vehicle','transport','Diesel, BS-VI (demo data)','City and intercity / Stop-start',['startstop','longhours','hot'], truck, 'Ashok Leyland Viking'),
      E('mahindra','Bolero Pik-Up','Fleet Vehicle','Commercial Vehicles','vehicle','transport','Diesel (demo data)','Last-mile fleet / Stop-start',['startstop','heavy'], [L('engine', ['superfleet-supreme','super-duty'], 7, 400), L('differential', ['gear-ep'], 3, 1500), L('grease', ['crown-lc'], 1, 100)], 'Mahindra Bolero Pik-Up'),
      E('atlas-copco','GA 37','Screw Compressor','Industrial','equipment','manufacturing','Electric drive (demo data)','Plant utility / Continuous duty',['hot','longhours'], [L('compressor', ['compressor-oil'], 20, 4000), L('grease', ['crown-lc'], 1, 2000)], 'Atlas Copco GA 37'),
      E('generic','Hydraulic Power Pack','Hydraulic System','Industrial','equipment','manufacturing','Electric drive (demo data)','Factory / Continuous duty',['hydraulic','longhours'], [L('hydraulic', ['harmony-aw','harmony-hvi'], 200, 4000)], 'Hydraulic Power Pack'),
      E('generic','Steam Turbine','Turbine','Industrial','equipment','power','Not applicable','Power plant / Continuous duty',['longhours','corrosion'], [L('turbine', ['turbine-oil'], 2000, 8000)], 'Steam Turbine'),
      E('elecon','Helical Gearbox','Gearbox','Industrial','equipment','manufacturing','Not applicable','Conveyor and mill drives / Heavy load',['heavy','longhours'], [L('gearbox', ['ep-lubricant'], 60, 4000), L('grease', ['crown-lc'], 1, 1000)], 'Elecon Helical Gearbox'),
      E('generic','Injection Moulding Machine','Manufacturing Equipment','Industrial','equipment','manufacturing','Electric drive (demo data)','Factory / Multi-shift',['hydraulic','hot','longhours'], [L('hydraulic', ['harmony-hvi','harmony-aw'], 400, 4000), L('grease', ['crown-lc'], 1, 500)], 'Injection Moulding Machine'),
      E('cummins','Diesel Genset 250 kVA','Diesel Genset','Industrial','equipment','power','Diesel (demo data)','Standby and prime power',['longhours','hot'], [L('engine', ['superfleet-supreme','super-duty','superfleet-synth'], 28, 250)], 'Cummins Diesel Genset 250 kVA'),
      E('tata-motors','Nexon','Passenger Car','Passenger & Two-wheelers','vehicle','automotive','Petrol / Diesel (demo data)','City and highway',['startstop','normal'], [L('engine', ['formula-gx','ultrasynth-x','multi-g'], 4, 300), L('transmission', ['gear-ep'], 2, 1500)], 'Tata Nexon'),
      E('maruti-suzuki','Swift','Passenger Car','Passenger & Two-wheelers','vehicle','automotive','Petrol (demo data)','City driving',['startstop','fuel'], [L('engine', ['ultrasynth-x','formula-gx','multi-g'], 3, 300)], 'Maruti Suzuki Swift'),
      E('hero','Splendor Plus','Motorcycle','Passenger & Two-wheelers','vehicle','automotive','Petrol, 4-stroke (demo data)','City commuting',['startstop','fuel'], [L('engine', ['pride-4t','syntrac-4t'], 1, 100)], 'Hero Splendor Plus'),
      E('honda','Activa','Scooter','Passenger & Two-wheelers','vehicle','automotive','Petrol, 4-stroke (demo data)','City commuting',['startstop','fuel'], [L('engine', ['pride-scooter'], 1, 100)], 'Honda Activa')
    ];
  })(),

  // ---- Oil analysis (DEMO limits and reports) ------------------------
  // dir 'high' = higher is worse; 'low' = lower is worse; 'band' = deviation from nominal viscosity (%).
  oilParams: [
    { id:'visc', name:'Viscosity', unit:'cSt', dir:'band', watch:8, action:15, meaning:'Viscosity outside the expected band can point to fuel dilution, oxidation or mixing with another grade.', actions:['Confirm the correct grade is in use','Check for fuel dilution or top-up with a different oil','Resample at the next interval'], article:'reading-an-oil-analysis-report' },
    { id:'fe', name:'Iron', unit:'ppm', dir:'high', watch:25, action:50, meaning:'Elevated iron may indicate increased wear within the lubricated system. Monitor the trend and inspect operating conditions if the value continues to rise.', actions:['Monitor next sample','Check filtration','Review operating conditions','Consult Gulf technical specialist'], article:'high-iron-in-engine-oil' },
    { id:'cu', name:'Copper', unit:'ppm', dir:'high', watch:15, action:30, meaning:'Copper can come from bearings, bushings or oil coolers. A rising trend matters more than a single value.', actions:['Compare with previous samples','Inspect cooler and bearing condition if rising'], article:'reading-an-oil-analysis-report' },
    { id:'al', name:'Aluminium', unit:'ppm', dir:'high', watch:10, action:20, meaning:'Aluminium may relate to piston or housing wear, or to dirt when it rises together with silicon.', actions:['Check alongside silicon','Inspect air intake if both rise'], article:'reading-an-oil-analysis-report' },
    { id:'si', name:'Silicon', unit:'ppm', dir:'high', watch:15, action:25, meaning:'Silicon usually signals dust or dirt entering the system, most often through the air intake or breathers.', actions:['Inspect air filter and intake hoses','Check breathers and seals','Shorten sampling interval'], article:'silicon-and-dust-ingress' },
    { id:'water', name:'Water', unit:'%', dir:'high', watch:0.1, action:0.2, meaning:'Water reduces lubricant film strength and promotes corrosion. Sources include condensation, coolant leaks and washing.', actions:['Check for coolant leak or condensation','Inspect seals and breathers','Change oil if confirmed'], article:'reading-an-oil-analysis-report' },
    { id:'oxidation', name:'Oxidation', unit:'abs/cm', dir:'high', watch:15, action:25, meaning:'Oxidation rises as oil ages, faster at high temperature. High values mean the oil is nearing the end of its useful life.', actions:['Review operating temperature','Review drain interval'], article:'high-oil-temperature-causes' },
    { id:'tbn', name:'TBN', unit:'mg KOH/g', dir:'low', watch:6, action:4, meaning:'Total Base Number shows the remaining reserve to neutralise acids. A low value means the oil is close to exhausted.', actions:['Plan oil change','Review fuel quality and drain interval'], article:'extending-drain-intervals-safely' },
    { id:'tan', name:'TAN', unit:'mg KOH/g', dir:'high', watch:2.5, action:3.5, meaning:'Total Acid Number rises as the oil degrades. A sharp rise suggests oxidation or contamination.', actions:['Compare with TBN and oxidation','Plan oil change if rising'], article:'reading-an-oil-analysis-report' },
    { id:'pc', name:'Particle count', unit:'ISO code', dir:'high', watch:20, action:22, meaning:'Particle count measures cleanliness. Hydraulic systems are especially sensitive to particles.', actions:['Check filter condition and rating','Review top-up practice and storage'], article:'hydraulic-oil-overheating' }
  ],
  oilAnalysis: [
    { id:'OA-001', equipment:'jcb-3dx', system:'engine', product:'superfleet-supreme', date:'2026-06-14', hoursOnOil:240, equipmentHours:5060, viscNominal:14.5, values:{ visc:14.4, fe:12, cu:4, al:3, si:8, water:0.02, oxidation:8, tbn:8.6, tan:1.4, pc:17 } },
    { id:'OA-002', equipment:'jcb-3dx', system:'engine', product:'superfleet-supreme', date:'2026-07-18', hoursOnOil:250, equipmentHours:5320, viscNominal:14.5, values:{ visc:14.2, fe:16, cu:5, al:3, si:9, water:0.03, oxidation:9, tbn:8.2, tan:1.6, pc:17 } },
    { id:'OA-003', equipment:'jcb-3dx', system:'engine', product:'superfleet-supreme', date:'2026-08-22', hoursOnOil:245, equipmentHours:5580, viscNominal:14.5, values:{ visc:14.0, fe:21, cu:6, al:4, si:11, water:0.03, oxidation:10, tbn:7.9, tan:1.7, pc:18 } },
    { id:'OA-004', equipment:'jcb-3dx', system:'engine', product:'superfleet-supreme', date:'2026-09-25', hoursOnOil:80, equipmentHours:5820, viscNominal:14.5, values:{ visc:13.8, fe:28, cu:7, al:5, si:13, water:0.05, oxidation:11, tbn:7.6, tan:1.8, pc:18 } },
    { id:'OA-005', equipment:'cat-320d', system:'hydraulic', product:'harmony-hvi', date:'2026-09-10', hoursOnOil:900, equipmentHours:7400, viscNominal:46, values:{ visc:45.1, fe:6, cu:3, al:1, si:5, water:0.02, oxidation:5, tbn:0, tan:0.6, pc:18 } },
    { id:'OA-006', equipment:'tata-motors-signa', system:'engine', product:'superfleet-supreme', date:'2026-09-02', hoursOnOil:480, equipmentHours:9100, viscNominal:14.5, values:{ visc:14.9, fe:19, cu:5, al:4, si:9, water:0.03, oxidation:14, tbn:5.4, tan:2.2, pc:18 } },
    { id:'OA-007', equipment:'atlas-copco-ga-37', system:'compressor', product:'compressor-oil', date:'2026-08-30', hoursOnOil:2100, equipmentHours:15200, viscNominal:46, values:{ visc:46.8, fe:3, cu:2, al:1, si:4, water:0.03, oxidation:9, tbn:0, tan:0.9, pc:17 } },
    { id:'OA-008', equipment:'mahindra-575-di', system:'engine', product:'tractor-engine', date:'2026-09-18', hoursOnOil:230, equipmentHours:3200, viscNominal:14.5, values:{ visc:14.1, fe:34, cu:8, al:12, si:31, water:0.04, oxidation:12, tbn:6.8, tan:2.0, pc:19 } }
  ],

  // ---- Sample passport history (shown when JCB 3DX is added) ---------
  maintenanceEvents: [
    { equipment:'jcb-3dx', date:'2026-09-12', type:'change', system:'engine', product:'superfleet-supreme', title:'Oil changed', notes:'Engine oil and filter replaced.', hours:5740 },
    { equipment:'jcb-3dx', date:'2026-09-20', type:'sample', system:'engine', title:'Oil sample collected', notes:'Sample sent for analysis.', hours:5810 },
    { equipment:'jcb-3dx', date:'2026-09-25', type:'analysis', system:'engine', title:'Oil analysis completed', notes:'Report OA-004 received.', ref:'OA-004', hours:5820 },
    { equipment:'jcb-3dx', date:'2026-09-25', type:'flag', system:'engine', title:'Iron level flagged', notes:'Iron 28 ppm, status WATCH.', ref:'OA-004', hours:5820 },
    { equipment:'jcb-3dx', date:'2026-09-26', type:'advice', system:'engine', title:'Technical recommendation generated', notes:'Monitor next sample, check filtration and air intake.', hours:5820 },
    { equipment:'jcb-3dx', date:'2026-09-30', type:'maintenance', system:'engine', title:'Maintenance completed', notes:'Air filter replaced, intake hoses inspected.', hours:5860 }
  ],

  // ---- Technical knowledge -------------------------------------------
  knowledgeCategories: ['Lubrication Basics','Engine Oils','Hydraulic Fluids','Gear Oils','Greases','Oil Analysis','Equipment Maintenance','EV Fluids','Industrial Lubrication','Troubleshooting','Specifications','OEM Requirements'],
  technicalArticles: [
    { id:'lubrication-basics-what-oil-does', title:'What does a lubricant actually do?', category:'Lubrication Basics', summary:'The five jobs every lubricant performs, and why the right grade matters.', body:['A lubricant separates moving surfaces with a film, carries heat away, keeps contaminants in suspension, protects against corrosion and, in hydraulic systems, transmits power.','Viscosity is the property that decides film thickness. Too thin and surfaces touch under load; too thick and the oil cannot reach tight clearances quickly, especially at start-up.','Stop-start duty is hard on oil because the film has to re-form at every start. That is why duty cycle, not only engine size, matters when choosing a product.'], systems:['engine'], equipment:['hero-splendor-plus','tata-motors-nexon'], products:['pride-4t','formula-gx'], problems:['frequent-start-stop'], params:[] },
    { id:'choosing-diesel-engine-oil-viscosity', title:'Choosing a diesel engine oil for heavy-duty work', category:'Engine Oils', summary:'How load, temperature and drain interval shape the choice of grade and performance level.', body:['Heavy-duty diesel engines work under sustained load, so the oil has to control soot, resist thickening and keep its viscosity at high temperature.','The viscosity grade is chosen for the ambient and operating temperature range. The performance level, such as an API category, is chosen to match what the engine maker specifies.','Lower-viscosity synthetic grades can support fuel economy and longer drains, but only where the engine maker allows that grade.'], systems:['engine'], equipment:['jcb-3dx','cat-320d','tata-motors-signa'], products:['superfleet-supreme','superfleet-synth','super-duty'], problems:['heavy-load','fuel-efficiency'], params:['visc','tbn'] },
    { id:'hydraulic-oil-overheating', title:'Why does hydraulic oil overheat?', category:'Hydraulic Fluids', summary:'Common causes of high hydraulic oil temperature and what to check first.', body:['Hydraulic oil heats up when energy is lost inside the system: internal leakage in worn pumps and valves, relief valves that open too often, or restrictions in lines and filters.','Low oil level, a blocked cooler or the wrong viscosity grade make it worse. Oil that is too thin leaks internally; oil that is too thick creates drag.','Check oil level and cooler condition first, then filters, then pressure settings. An oil analysis sample will show whether the fluid itself has oxidised or picked up contamination.'], systems:['hydraulic'], equipment:['jcb-3dx','cat-320d','hydraulic-power-pack'], products:['harmony-hvi','harmony-aw'], problems:['high-oil-temperature','hydraulic-performance'], params:['oxidation','pc','visc'] },
    { id:'gear-oil-gl4-vs-gl5', title:'GL-4 and GL-5 gear oils: what is the difference?', category:'Gear Oils', summary:'Why axle oils and some gearbox oils are not interchangeable.', body:['API GL-4 and GL-5 describe the level of extreme-pressure protection in a gear oil. GL-5 oils carry more extreme-pressure additive for heavily loaded hypoid axles.','Some synchronised gearboxes specify GL-4 because of the materials used in the synchronisers. Using the specified category matters more than choosing the higher number.','Always follow the category the equipment maker lists for each component.'], systems:['transmission','differential'], equipment:['tata-motors-signa','mahindra-575-di'], products:['gear-ep','utto'], problems:['wear-protection'], params:['fe'] },
    { id:'grease-selection-nlgi', title:'How to choose a grease', category:'Greases', summary:'Thickener, base oil and NLGI grade in plain terms.', body:['A grease is base oil held in a thickener. The NLGI grade describes how stiff it is; NLGI 2 is the common general-purpose consistency.','The thickener type affects temperature range and water resistance. Mixing greases with different thickeners can cause softening, so purge or check compatibility when changing product.','Pins and bushes on construction equipment need frequent greasing because dust and shock load push grease out.'], systems:['grease'], equipment:['jcb-3dx','cat-950'], products:['crown-lc'], problems:['dust-contamination'], params:[] },
    { id:'reading-an-oil-analysis-report', title:'How to read an oil analysis report', category:'Oil Analysis', summary:'Wear metals, contaminants and oil condition, and why the trend matters more than one number.', body:['A report has three groups of results: wear metals such as iron and copper, contaminants such as silicon and water, and oil condition such as viscosity, oxidation, TBN and TAN.','A single result tells you little. The value of oil analysis is the trend across samples taken at similar hours on oil.','Each result is compared with limits to give a status. A WATCH status asks for closer monitoring; ACTION REQUIRED asks for inspection or an oil change.'], systems:['engine','hydraulic'], equipment:['jcb-3dx','tata-motors-signa'], products:['superfleet-supreme'], problems:['corrosion-protection'], params:['fe','cu','si','water','visc','tbn','tan'] },
    { id:'high-iron-in-engine-oil', title:'High iron in engine oil: what it means', category:'Oil Analysis', summary:'Where iron comes from and what to do when it rises.', body:['Iron in used engine oil comes mainly from cylinder liners, rings, camshafts and gears. Some iron is normal and rises with hours on oil.','Iron that is high for the hours on oil, or rising from sample to sample, is an early warning. Check whether silicon is rising too, because dust entering through the air intake is a common cause of wear.','The usual response is to monitor the next sample, check filtration and air intake, review operating conditions and confirm the oil meets the specification the engine maker requires.'], systems:['engine'], equipment:['jcb-3dx','mahindra-575-di'], products:['superfleet-supreme','tractor-engine'], problems:['wear-protection'], params:['fe','si'] },
    { id:'silicon-and-dust-ingress', title:'Silicon and dust ingress', category:'Troubleshooting', summary:'How dust gets into engines and hydraulic systems, and how to stop it.', body:['Silicon in an oil sample usually means dirt. In engines it enters through a damaged air filter, loose intake hose or poor filter servicing.','Dust is abrasive, so silicon and wear metals often rise together. Fixing the entry point is more effective than changing oil more often.','In hydraulic systems, check breathers, cylinder rod seals and top-up practice.'], systems:['engine','hydraulic'], equipment:['mahindra-575-di','komatsu-pc210','jcb-3dx'], products:['tractor-engine','superfleet-supreme'], problems:['dust-contamination'], params:['si','al','fe'] },
    { id:'extending-drain-intervals-safely', title:'Extending drain intervals safely', category:'Equipment Maintenance', summary:'Why drain extension should be earned with data.', body:['A longer drain interval reduces oil, filter, labour and downtime cost, but only if the oil is still protecting the engine at the end of the interval.','The safe way to extend is in steps, with oil analysis at each step to confirm that TBN, viscosity, oxidation and wear metals stay within limits.','The equipment maker’s maximum interval always applies, whatever the oil.'], systems:['engine'], equipment:['tata-motors-signa','ashok-leyland-viking'], products:['superfleet-synth','superfleet-supreme'], problems:['long-drain-interval'], params:['tbn','oxidation','visc'] },
    { id:'ev-fluids-explained', title:'EV fluids explained', category:'EV Fluids', summary:'What electric vehicles still need from a fluid.', body:['Electric vehicles have no engine oil, but they still use fluids in reduction gearboxes, e-axles and thermal management.','Where the fluid touches the motor, it has to be compatible with copper windings and insulation and have suitable electrical properties, as well as protecting gears and bearings.','This is a developing area. Product scope should be confirmed with the technical team for each vehicle platform.'], systems:['ev'], equipment:['tata-motors-nexon'], products:['elec-driveline'], problems:['fuel-efficiency'], params:[] },
    { id:'industrial-gearbox-lubrication', title:'Industrial gearbox lubrication basics', category:'Industrial Lubrication', summary:'Viscosity grade, extreme-pressure protection and cleanliness for enclosed gear drives.', body:['Enclosed industrial gear drives are specified by ISO viscosity grade. The gearbox maker lists the grade for the speed, load and temperature of the drive.','Loaded gears need extreme-pressure protection. Water and particles shorten gear and bearing life, so breathers and seals matter as much as the oil.','Periodic oil analysis shows wear metals and contamination before damage becomes visible.'], systems:['gearbox'], equipment:['elecon-helical-gearbox'], products:['ep-lubricant'], problems:['heavy-load','wear-protection'], params:['fe','water','pc'] },
    { id:'high-oil-temperature-causes', title:'Why is my oil temperature increasing?', category:'Troubleshooting', summary:'A checklist for rising oil temperature in engines and hydraulic systems.', body:['Rising oil temperature usually has a mechanical or operating cause: low oil level, a blocked cooler or radiator, overloading, or a restriction in the system.','Oil condition can contribute. Oil that has oxidised or thickened carries heat less well, and the wrong viscosity grade increases friction or internal leakage.','Check level and cooling first. Then take an oil sample: oxidation, viscosity and wear metals will show whether the oil or the machine needs attention.'], systems:['engine','hydraulic'], equipment:['jcb-3dx','cat-320d','atlas-copco-ga-37'], products:['superfleet-supreme','harmony-hvi'], problems:['high-oil-temperature'], params:['oxidation','visc'] },
    { id:'understanding-api-acea-specifications', title:'Understanding API, ACEA and ISO VG', category:'Specifications', summary:'What the letters on the pack mean.', body:['API and ACEA categories describe engine oil performance. SAE grades such as 15W-40 describe viscosity, not quality.','ISO VG numbers describe the viscosity of industrial oils such as hydraulic and gear oils at 40°C.','A product is suitable only when it meets the category and grade the equipment maker specifies.'], systems:['engine','hydraulic','gearbox'], equipment:['jcb-3dx','hydraulic-power-pack'], products:['superfleet-supreme','harmony-aw','ep-lubricant'], problems:[], params:['visc'] },
    { id:'oem-requirements-and-approvals', title:'OEM requirements and approvals', category:'OEM Requirements', summary:'The difference between "meets the requirements of" and a formal approval.', body:['Equipment makers publish the specifications their machines need. Some also run formal approval programmes in which a specific product is tested and listed.','A formal approval is specific to a product and formulation. It should be quoted only with its reference, and checked against the current list.','In this prototype, approvals are deliberately left empty. In production they would be read from the technical database and linked to each OEM page.'], systems:['engine'], equipment:['jcb-3dx','cat-320d','tata-motors-signa'], products:['superfleet-supreme'], problems:[], params:[] }
  ],

  // ---- Local ecosystem (DEMO locations) -------------------------------
  distributors: [
    { id:'d1', name:'Gulf Authorized Distributor – Andheri East', city:'Mumbai', area:'Andheri East', pin:'400093', services:'Bulk supply, technical visits', categories:'Automotive + Industrial', phone:'Demo: 022-0000 0001', hours:'Open today · 9:00–18:30' },
    { id:'d2', name:'Gulf Authorized Distributor – Vashi', city:'Mumbai', area:'Vashi', pin:'400703', services:'Retail supply', categories:'Automotive', phone:'Demo: 022-0000 0002', hours:'Open today · 9:30–19:00' },
    { id:'d3', name:'Gulf Authorized Distributor – Okhla', city:'Delhi', area:'Okhla', pin:'110020', services:'Bulk supply, oil sampling kits', categories:'Automotive + Industrial', phone:'Demo: 011-0000 0003', hours:'Open today · 9:00–18:30' },
    { id:'d4', name:'Gulf Authorized Distributor – Peenya', city:'Bengaluru', area:'Peenya', pin:'560058', services:'Industrial supply, technical visits', categories:'Industrial', phone:'Demo: 080-0000 0004', hours:'Open today · 9:00–18:00' },
    { id:'d5', name:'Gulf Authorized Distributor – Chakan', city:'Pune', area:'Chakan', pin:'410501', services:'Fleet supply, bulk supply', categories:'Commercial Vehicles + Industrial', phone:'Demo: 020-0000 0005', hours:'Open today · 9:00–18:30' },
    { id:'d6', name:'Gulf Authorized Distributor – Ambattur', city:'Chennai', area:'Ambattur', pin:'600058', services:'Bulk supply', categories:'Automotive + Industrial', phone:'Demo: 044-0000 0006', hours:'Open today · 9:00–18:30' }
  ],
  garages: [
    { id:'g1', name:'Gulf Garage – Powai', city:'Mumbai', area:'Powai', pin:'400076', services:'Oil change, general service', categories:'Cars + Two-wheelers', phone:'Demo: 022-0000 0101', hours:'Open today · 9:00–20:00' },
    { id:'g2', name:'Gulf Garage – Thane West', city:'Mumbai', area:'Thane West', pin:'400601', services:'Oil change, fleet service', categories:'Cars + Commercial vehicles', phone:'Demo: 022-0000 0102', hours:'Open today · 9:00–19:30' },
    { id:'g3', name:'Gulf Garage – Karol Bagh', city:'Delhi', area:'Karol Bagh', pin:'110005', services:'Oil change', categories:'Two-wheelers', phone:'Demo: 011-0000 0103', hours:'Open today · 9:30–20:00' },
    { id:'g4', name:'Gulf Garage – Whitefield', city:'Bengaluru', area:'Whitefield', pin:'560066', services:'Oil change, general service', categories:'Cars + Two-wheelers', phone:'Demo: 080-0000 0104', hours:'Open today · 9:00–20:00' },
    { id:'g5', name:'Gulf Garage – Hadapsar', city:'Pune', area:'Hadapsar', pin:'411028', services:'Oil change, fleet service', categories:'Cars + Commercial vehicles', phone:'Demo: 020-0000 0105', hours:'Open today · 9:00–19:30' },
    { id:'g6', name:'Gulf Garage – Guindy', city:'Chennai', area:'Guindy', pin:'600032', services:'Oil change', categories:'Cars + Two-wheelers', phone:'Demo: 044-0000 0106', hours:'Open today · 9:00–20:00' }
  ],

  // ---- Product authentication (DEMO codes) ----------------------------
  authCodes: {
    'GULF-2026-0417': { product:'superfleet-supreme', batch:'Demo batch B-2607', mfg:'Demo: July 2026, Silvassa plant', pack:'20 L' },
    'GULF-2026-0822': { product:'harmony-hvi', batch:'Demo batch H-2608', mfg:'Demo: August 2026, Chennai plant', pack:'210 L' },
    'GULF-2026-1105': { product:'pride-4t', batch:'Demo batch P-2609', mfg:'Demo: September 2026, Silvassa plant', pack:'1 L' }
  },

  // ---- Seed numbers for the analytics dashboard (DEMO) ----------------
  analyticsSeed: { equipment:{ 'JCB 3DX':42, 'Tata Signa':31, 'CAT 320D':24, 'Mahindra 575 DI':19 }, products:{ 'Gulf Superfleet Supreme':57, 'Gulf Harmony HVI':33, 'Gulf Pride 4T Plus':29, 'Gulf Gear EP':18 }, problems:{ 'High oil temperature':26, 'Wear protection':21, 'Dusty environment':17, 'Long drain interval':12 }, modules:{ 'Product Finder':140, 'AI Advisor':96, 'Equipment Database':88, 'Oil Analysis':41, 'TCO Calculator':37, 'Lubrication Passport':29, 'Technical Knowledge':73 }, leads:{ started:38, submitted:21 } }
};

// Specifications are derived from products so there is a single source of truth.
gulfData.specifications = [...new Set(gulfData.products.flatMap(p => p.specs.concat(/^\d+W/.test(p.grade) ? ['SAE ' + p.grade] : [])))].sort()
  .map(name => ({ id: slugify(name), name, family: ['ISO VG','API','ACEA','JASO','ILSAC','DIN','NLGI','SAE'].find(f => name.startsWith(f)) || 'Other' }));
